CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_POINTING=y

CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=0

CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=5
CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=5
CONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=5

CONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
CONFIG_DONGLE_SCREEN_OUTPUT_ACTIVE=n
