manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: dmitryshalaev
      url-base: https://github.com/DmitryShalaev
  projects:
    - name: ergohaven-zmk-qube
      remote: dmitryshalaev
      revision: a577a329b9f1fd176edefed67f6c565351bc484b
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
  self:
    path: config
