manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: dmitryshalaev
      url-base: https://github.com/DmitryShalaev
  projects:
    - name: ergohaven-zmk-qube
      remote: dmitryshalaev
      revision: 500e3a6b049e8404772a35648981e62605fd2fac
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
  self:
    path: config
